name: fastapi-realworld-ex
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip==20.0.2
    - pip:
        - uvicorn>=^0.11.3
        - fastapi>=^0.58.1
        - pydantic[email]>=^1.4
        - passlib[bcrypt]>=^1.7
        - pyjwt>=^1.7
        - asyncpg>=^0.20.1
        - aiosql>=^3.0.0
        - pypika>=^0.37.15
        - alembic>=^1.4
        - databases[postgresql]>=^0.3.2
        - python-slugify>=^4.0
        - Unidecode>=^1.1
        - loguru>=^0.5.1
        - black>=^19.10b0
        - isort>=^4.3
        - autoflake>=^1.3
        - wemake-python-styleguide>=^0.14.0
        - mypy>=^0.782
        - flake8-fixme>=^1.1
        - pytest>=^5.4
        - pytest-cov>=^2.10
        - pytest-asyncio>=^0.14.0
        - pytest-env>=^0.6.2
        - docker>=^4.2
        - httpx>=^0.13.3
        - asgi-lifespan>=^1.0.1
        - debugpy>=1.0.0b9